spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://teamnexters.ck1pcnhtmokh.ap-northeast-2.rds.amazonaws.com:3306/nextershp?useUnicode=true&characterEncoding=utf8
    username: hp
    password: hpqw12#$

   
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
  

  
  
server:
  port: 8020